대학교 메일 인증 추가
Glosseum/glosseum-api pull request #20
Opened 2024-01-14 05:27 UTC by mcgun1234

user/univ_verify에서 이메일로 인증 코드를 전송하고
user/register에서 그 코드까지 함께 입력하여 전송하는 방식으로 구현하였습니다!

2024-01-14 07:08 UTC, invalidid56 commented on config.py
> +UNIVCERT_API_KEY = os.getenv("UNIVCERT_API_KEY", "")
Github Secret에 이 키 추가해야 할 것 같아요

2024-01-14 07:08 UTC, invalidid56 commented on data/db/database.py
> -            async with async_session as session:
이 팩토리가 왜 이렇게 되어 있던 건지는 미스테리..

2024-01-14 07:08 UTC, invalidid56 commented on endpoint/user/route.py
> +        _user_create.code,
code 보다 더 명시적으로 이름 고치면 좋을 것 같아요

2024-01-14 07:08 UTC, invalidid56 commented on endpoint/user/service.py
> +    response = requests.post(univcert_url+"certifycode", json={"key": UNIVCERT_API_KEY, "email": email, "univName": "서울대학교", "code": code})
여기서 블락킹 일어나는데, 비동기로 보낼 수 있게 고쳐주세용

2024-01-14 07:08 UTC, invalidid56 commented on endpoint/user/service.py
> +        requests.post(univcert_url+"clear/"+user.email, json={"key": UNIVCERT_API_KEY})
마찬가지로 블락킹

2024-01-14 07:23 UTC, mcgun1234 commented on config.py
> +UNIVCERT_API_KEY = os.getenv("UNIVCERT_API_KEY", "")
추가하였습니다

2024-01-14 07:24 UTC, mcgun1234 commented on endpoint/user/route.py
> +        _user_create.code,
고쳤습니다

2024-01-14 16:29 UTC, mcgun1234 commented
@invalidid56 모든 버그 해결하였습니다. 확인좀 부탁드려요

2024-01-22 11:56 UTC, invalidid56 approved these changes
LGTM입니당~ 

다음 수정부터 반영되면 좋을만한 것
- 기능 단위별로 브랜치 나누기 (이메일이랑 여러 리팩터링 사항이 혼재)

근데 이번엔 사실 급했어서 어쩔 수 없죠 ㅎㅎ 수고하셨습니다!

2024-01-22 11:56 UTC, invalidid56 commented on data/db/database.py
> +            async with async_session() as session:
👍

2024-01-22 11:58 UTC, invalidid56 requested changes
Merge Conflict 해결해주세요~

2024-01-24 14:23 UTC, merged